services:
  - type: web
    name: raichuru-belaku
    env: static
    buildCommand: npm ci && npx vite build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html