services:
  - type: web
    name: raichuru-belaku
    env: static
    buildCommand: npm ci && chmod +x node_modules/.bin/vite && ./node_modules/.bin/vite build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html