services:
  - type: web
    name: raichuru-belaku
    env: static
    buildCommand: npm ci && node node_modules/vite/bin/vite.js build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html